export const yearOptions = {
    "0no-year": "No year selected",
    "1freshman": "Freshman (1st year)",
    "2sophomore": "Sophomore (2nd year)",
    "3junior": "Junior (3rd year)",
    "4senior": "Senior (4th year)",
    "5super-senior": "Super-senior (4th year+)"
}

export const majorOptions = {
    "0no-major": "No major selected",
    "accounting": "Accounting",
    "advertising": "Advertising",
    "aerospace engineering": "Aerospace Engineering",
    "african languages": "African Languages",
    "african-american studies": "African-American Studies",
    "agricultural education and communication": "Agricultural Education and Communication",
    "agricultural operations management": "Agricultural Operations Management",
    "animal sciences": "Animal Sciences",
    "anthropology": "Anthropology",
    "applied physiology and kinesiology": "Applied Physiology and Kinesiology",
    "arabic": "Arabic",
    "architecture": "Architecture",
    "art history": "Art History",
    "art ": "Art ",
    "astronomy and astrophysics": "Astronomy and Astrophysics",
    "biological engineering": "Biological Engineering",
    "biology ": "Biology ",
    "botany": "Botany",
    "chemical engineering": "Chemical Engineering",
    "chemistry | biochemistry": "Chemistry | Biochemistry",
    "chinese": "Chinese",
    "civil engineering": "Civil Engineering",
    "classical studies": "Classical Studies",
    "communication sciences and disorders": "Communication Sciences and Disorders",
    "computer engineering": "Computer Engineering",
    "computer science ": "Computer Science ",
    "construction management": "Construction Management",
    "criminology": "Criminology",
    "dance ": "Dance ",
    "data science": "Data Science",
    "dietetics": "Dietetics",
    "digital arts and sciences ": "Digital Arts and Sciences ",
    "disabilities in society specialization": "Disabilities in Society Specialization",
    "dual languages": "Dual Languages",
    "economics": "Economics",
    "education sciences": "Education Sciences",
    "education | unified early childhood education proteach | pre-k-grade 3": "Education | Unified Early Childhood Education ProTeach | Pre-K-Grade 3",
    "educational psychology and research": "Educational Psychology and Research",
    "educational technology": "Educational Technology",
    "electrical engineering": "Electrical Engineering",
    "elementary education | grades k-6": "Elementary Education | Grades K-6",
    "emergency management": "Emergency Management",
    "emergency medical services management": "Emergency Medical Services Management",
    "engineering | exploring engineering studies": "Engineering | Exploring Engineering Studies",
    "english": "English",
    "entomology and nematology": "Entomology and Nematology",
    "environmental engineering": "Environmental Engineering",
    "environmental management in agriculture and natural resources | interdisciplinary studies": "Environmental Management in Agriculture and Natural Resources | Interdisciplinary Studies",
    "environmental science": "Environmental Science",
    "family, youth and community sciences": "Family, Youth and Community Sciences",
    "finance": "Finance",
    "fire management": "Fire Management",
    "food and resource economics": "Food and Resource Economics",
    "food science": "Food Science",
    "foreign languages and literatures": "Foreign Languages and Literatures",
    "forest resources and conservation": "Forest Resources and Conservation",
    "french and francophone studies": "French and Francophone Studies",
    "general studies": "General Studies",
    "geographical science and sustainability ": "Geographical Science and Sustainability ",
    "geography": "Geography",
    "geology": "Geology",
    "geomatics": "Geomatics",
    "german": "German",
    "graphic design": "Graphic Design",
    "health education and behavior": "Health Education and Behavior",
    "health science": "Health Science",
    "hebrew": "Hebrew",
    "hispanic and latin american languages, literatures and linguistics": "Hispanic and Latin American Languages, Literatures and Linguistics",
    "history": "History",
    "horticultural science": "Horticultural Science",
    "industrial and systems engineering": "Industrial and Systems Engineering",
    "information systems": "Information Systems",
    "interdisciplinary studies | clas": "Interdisciplinary Studies | CLAS",
    "interior design": "Interior Design",
    "international studies": "International Studies",
    "italian": "Italian",
    "japanese": "Japanese",
    "jewish studies": "Jewish Studies",
    "journalism": "Journalism",
    "landscape architecture | 5-year professional program": "Landscape Architecture | 5-Year Professional Program",
    "linguistics": "Linguistics",
    "management": "Management",
    "marine sciences": "Marine Sciences",
    "marketing": "Marketing",
    "materials science and engineering": "Materials Science and Engineering",
    "mathematics": "Mathematics",
    "mechanical engineering": "Mechanical Engineering",
    "media production, management, and technology": "Media Production, Management, and Technology",
    "microbiology and cell science": "Microbiology and Cell Science",
    "music education": "Music Education",
    "music": "Music",
    "natural resource conservation": "Natural Resource Conservation",
    "nuclear and radiological sciences": "Nuclear and Radiological Sciences",
    "nuclear engineering": "Nuclear Engineering",
    "nursing": "Nursing",
    "nutritional sciences": "Nutritional Sciences",
    "pharmacy | preprofessional": "Pharmacy | Preprofessional",
    "philosophy": "Philosophy",
    "physics": "Physics",
    "plant science": "Plant Science",
    "political science": "Political Science",
    "portuguese": "Portuguese",
    "psychology": "Psychology",
    "public health": "Public Health",
    "public relations": "Public Relations",
    "religion": "Religion",
    "russian": "Russian",
    "schools, society and policy": "Schools, Society and Policy",
    "sociology": "Sociology",
    "soil and water sciences": "Soil and Water Sciences",
    "spanish": "Spanish",
    "spanish and portuguese": "Spanish and Portuguese",
    "sport management": "Sport Management",
    "statistics": "Statistics",
    "sustainability and the built environment": "Sustainability and the Built Environment",
    "sustainability studies": "Sustainability Studies",
    "theatre": "Theatre",
    "theatre performance": "Theatre Performance",
    "theatre production": "Theatre Production",
    "tourism, hospitality and event management": "Tourism, Hospitality and Event Management",
    "wildlife ecology and conservation": "Wildlife Ecology and Conservation",
    "women's studies": "Women's Studies",
    "zoology": "Zoology"
}

export const personalityOptions = {
    "0no-preferenece": "No preference",
    "1extremely-introverted": "Extremely introverted",
    "2very-introvreted": "Very introverted",
    "3introverted": "Introverted",
    "4slightly-introverted": "Slightly introverted",
    "5neutral": "Neutral",
    "6slightly-extroverted": "Slightly extroverted",
    "7extroverted": "Extroverted",
    "8very-extroverted": "Very extroverted",
    "9extremely-extroverted": "Extremely extroverted"
}

export const studyHabitOptions = {
    "0no-preferenece": "No preference",
    "1worst": "I don't study.",
    "2bad": "The day before or the day of the test.",
    "3mid": "The week of the test. ",
    "4good": "The week before a test.",
    "5best": "Weeks in advance."
}

export const studyTimeOptions = {
    "0no-preferenece": "No preference",
    "1early morning": "early morning (~5am-8am)",
    "2morning": "morning (~8am-11am)",
    "3noon": "noon (~11am-2pm)",
    "4afternoon": "afternoon (~2pm-5pm)",
    "5evening": "early evening (~5pm-8pm)",
    "6late-evening": "late-evening (~8pm-11pm)",
    "7midnight": "midnight (~11pm-2am)",
    "8past-midnight": "past midngiht (~2am-5am)"
}
